version: 0.2

phases:
  pre_build:
    commands:
      - echo "Before running tests"
      - yum install -y gcc-c++
      - yum install -y mysql-devel
      - pip install -r requirements.txt
      
  build:
    commands:
      - echo "Starting Migrations"
      - python manage.py migrate
      - echo "Starting Server"
      - python manage.py runserver > /dev/null 2>&1 &
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*' 